### ISSUE TITLE
Notifications is completely empty

### ISSUE THREAD

**Issue by Cuteminded** [ProbablyRaging/hide-youtube-shorts#1]
if you have the exstension on with "Home & Subscription Feed" the Notifications drop down is completely empty

![Oxnxo1b](https://user-images.githubusercontent.com/23005387/216188337-3158a4f1-92d0-4147-a250-abb9121ffa9e.png)

**Comment by zevnda** [comment]
I am unable to reproduce this issue.

The only thing I can suggest is making sure you're using the most up-to-date version of Chrome and Hide YouTube Shorts. Check if there is a conflict with another extension. Reinstalling the extension

**Comment by Cuteminded** [comment]
Chrome : 109.0.5414.119
Extension : 1.2.1

I also took a look on another account and it only happens when there are one or more shorts in the notifications menu

**Comment by zevnda** [comment]
Thank you. I was still unable to repro your exact issue., however, I do see that the extension interacts with the notification menu in some other way.

Notifications regarding shorts seem to display fine, on my end at least. Though, I have put something in place that I am hoping will ignore shorts elements in the notification menu altogether but I'm unable to thoroughly test it as there are many factors to cover.

33acda14b35bebc0a956f2a21b8a25fa89cbfe36 will be available in v1.2.2 of the extension/

![image](https://user-images.githubusercontent.com/24839609/216380521-5611dffc-1629-46de-b2d9-c72cee015501.png)
