### ISSUE TITLE
Shorts still show on the hashtag page.

### ISSUE THREAD

**Issue by sapondanaisriwan** [ProbablyRaging/hide-youtube-shorts#10]
### Describe the issue

https://www.youtube.com/hashtag/shorts
![msedge_skUWVgEjyw](https://user-images.githubusercontent.com/64634605/235365709-3f930d92-3a4a-4845-828e-9a2d8519e1f0.png)

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Microsoft Edge

### Latest browser version?

Yes

**Comment by Ice-mourne** [comment]
Pr I made can solve that if my code is enabled not just for subscriptions it is only for a sub because of lack of testing elsewhere

**Comment by zevnda** [comment]
Thanks for the report.

This page is almost entirely dedicated to displaying shorts content. AFAIK it only accessible via clicking the #shorts link and is not accessible through the navigation menu. You'd be best to just not visit that page if you don't want to see shorts. I won't be adding a feature to hide shorts on this page.
