### ISSUE TITLE
No longer works with subscription feed update

### ISSUE THREAD

**Issue by carlodrift** [ProbablyRaging/hide-youtube-shorts#12]
### Describe the issue

Shorts are no longer removed with the new subscription feed interface

<img width="1370" alt="image" src="https://github.com/ProbablyRaging/hide-youtube-shorts/assets/30211659/0bfb0b25-998d-4d4a-910d-469820bbf0b9">

### What version of HYS are you using?

1.5.0

### What browsers are you seeing the problem on?

Chrome, Brave

### Latest browser version?

Yes

**Comment by jmaysnc** [comment]
Can confirm. Having the same issue.

**Comment by zevnda** [comment]
Same issue as #6. This is due to UI changes on YouTube and as of right now I have no plans to fix it as it is only a treatment at the moment and only a small group of users have access to it. This issue will be solved if/when YouTube decide to make these UI changes global.
