### ISSUE TITLE
The extension is deleting all my subscription videos

### ISSUE THREAD

**Issue by BobaladinsRTX** [ProbablyRaging/hide-youtube-shorts#14]
### Describe the issue

The extension is progressively deleting videos from my subscription page, leaving only the "this week/month" / "last month" tabs
![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/61839216/0e7d16ee-349e-41e8-a788-2cc46681053c)

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by zevnda** [comment]
> ### Describe the issue
> The extension is progressively deleting videos from my subscription page, leaving only the "this week/month" / "last month" tabs

Does your Subscriptions page contain any regular videos?
Can you disable the extension refresh the page and show me a screenshot please.

**Comment by BobaladinsRTX** [comment]
[image: image.png]
The page is just as usual (with shorts)

Le mer. 7 juin 2023 à 13:14, ProbablyRaging ***@***.***> a
écrit :

**Comment by zevnda** [comment]
Thank you for the heads up!

This is fixed in 1.6.2 with cad1f0c63d92c96393dcca5b7674d090467b3996

You can download the .zip from this repo and load the unpacked version, or wait for the update to go live on CWS within ~24 hurs

**Comment by rowanbane** [comment]
This is also happening for me - I will open subscriptions and videos including shorts will briefly appear then be removed over the span of a few seconds until only much older videos appear.

It only started happening in the last 12 hours
