### ISSUE TITLE
Removing all videos on the Subscriptions page

### ISSUE THREAD

**Issue by cadtek91** [ProbablyRaging/hide-youtube-shorts#15]
### Describe the issue

When I open the subscriptions page, Hide YouTube Shorts will hide all videos under each section. Then the page will load more, and it'll remove them as well.

Browser: Chrome, Version 114.0.5735.110
HYS version: 1.6.1

See screen recording - [https://youtu.be/QViYpx0ZmcI](https://youtu.be/QViYpx0ZmcI)

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by cadtek91** [comment]
I just checked the _Closed_ tickets.  I see it's fixed here - [https://github.com/ProbablyRaging/hide-youtube-shorts/issues/14#issuecomment-1580649695](https://github.com/ProbablyRaging/hide-youtube-shorts/issues/14#issuecomment-1580649695)

**Comment by zevnda** [comment]
> I just checked the _Closed_ tickets. I see it's fixed here - [#14 (comment)](https://github.com/ProbablyRaging/hide-youtube-shorts/issues/14#issuecomment-1580649695)

Yep that's right. 1.6.2 should be live on CWS now. To update go to your browser > manage extensions > update
