### ISSUE TITLE
hide streams from feed

### ISSUE THREAD

**Issue by JoeBidenSleep** [ProbablyRaging/hide-youtube-shorts#16]
### Describe the feature

hide streams from feed option needed

**Comment by zevnda** [comment]
Thank you for the suggestions.

I actually tried to add a feature for this already a while back but unfortunately premieres and lives are rendered on the page as document fragments and are not directly editable via the DOM.

This might change with the new UI that is slowly rolling out though. I will leave this open until I can properly test on there.

**Comment by zevnda** [comment]
It would appear that the new UI doesn't render premieres and lives as document fragments anymore. Meaning they can definitely be removed from feed pages.

However, seeing as this new UI is still not a permanent change and only a small portion of users have access to it, I will have to hold off on adding a feature for this, but I will definitely add it in the future if the new UI sticks around.

I'll leave this feature request open for now. Thanks again for the suggestion!

**Comment by zevnda** [comment]
Decided to add this in 1.6.6 with b85beedaa3341b6c2fb8e24cea69aaaa7f376acc.

Added an option to hide Lives and Premieres on the Home and Subscription pages. It will only work with the new YouTube UI
