### ISSUE TITLE
shorts hidden, but tile still shows

### ISSUE THREAD

**Issue by themaskedcrusader** [ProbablyRaging/hide-youtube-shorts#17]
### Describe the issue

This used to hide the shorts completely, but now it just puts up a tile over the short saying the short was hidden by the extension. This kind of defeats the purpose of the extension as I still see where the shorts are even if I don't see the actual short. I assume it's due to an update at youtube, but thought I would submit this as a bug.
![Screenshot 2023-06-07 103448](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/886870/17efc55b-e914-4216-81dc-b5130824c26d)

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by zevnda** [comment]
> ### Describe the issue
> This used to hide the shorts completely, but now it just puts up a tile over the short saying the short was hidden by the extensi...

Thank you for the report. Unfortunately it looks like this is going to be an unavoidable issue.

YouTube released a new UI layout for the subscriptions page that renders videos in seperate grids. Each grid consists of a 4x1 row of videos. Previously, it used to just render them all in one big flex box so when you removed one video it would just fill the gap with another video. But with the new UI there are only 4 videos in the row so if you remove one, there is no other video to fill the gap.

I added an option to the Misc tab of the extension that lets you control if you want to see the "Hidden By HYS" tile or just a blank space.

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/24839609/f600dcdb-d876-4200-9747-9b1f6a8531cd)

As of right now I see no way of fixing this so I am going to close this issue I will continue to think of a better method and if I find one, I will update this issue.

**Comment by zevnda** [comment]
This is fixed in 1.6.7 with 56a664e847090713a9375ee7774f41e158f9d21b

Credit to HorsyNox for reaching out to me with a fix.

**Comment by themaskedcrusader** [comment]
Absolutely amazing! Works perfectly! You and Horsy Nox are Amazing!
