### ISSUE TITLE
Still showing shorts in my subscriptions feed

### ISSUE THREAD

**Issue by RobThree** [ProbablyRaging/hide-youtube-shorts#18]
### Describe the issue

I'm still seeing shorts in my subscriptions feed:

![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/607888/726cc786-d430-48c8-9a13-c13761c1d749)

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by zevnda** [comment]
I'm a little confused by the screenshot you've shared. It appears that your Subscriptions page is showing content from channels you're not subscribed to, or they don't appear in the Subscriptions list at the very least.

I also see that your Subscriptions list isn't in alphabetical order as it should be by default. Unless a channel is Live or has a current Premiering video it should be alphabatized. otherwise the channel would be at the top of the list with a red broadcasting icon next to it. However I see that the LTT channel is first in your list regardless of it being live/premiering.

The channels I have marked should appear somewhere in your list, but don't
![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/24839609/6336cc0b-4721-4ce5-83e7-208b59e0d45c)

Are you using any other extensions for YouTube that allow you to customize your subscriptions by any chance? This could likely cause conflicts between the two extensions.

Come to think of it, I don't recall ever seeing a Shorts Shelf on the Subscriptions page before and I am unable to get one to appear on my own no matter how hard I try, so this could very well be a new thing.

Could you go to the Subscriptions page > right click anywhere on the page > click "view page source", then copy the entire contents of the pages HTML, paste it into a .txt file and upload it here so I can take a look at it? Because as of right now I am unable to repro and no one has mentioned having this issue.

**Comment by RobThree** [comment]
> I'm a little confused by the screenshot you've shared. It appears that your Subscriptions page is showing content from channels you're not subscribed to, or they don't appear in the Subscriptions list at the very least.

I have over 200 subscriptions, they're not in alphabetical order:

- [Linus Tech Tips](https://www.youtube.com/@LinusTechTips)
- [Adrian's Digital Basement](https://www.youtube.com/@adriansdigitalbasement)
- [BOOS](https://www.youtube.com/@BOOS)
- [Cathode Ray Dude [CRD]](https://www.youtube.com/@CathodeRayDude)
- [Corridor Crew](https://www.youtube.com/@CorridorCrew)
- [StezStix Fix?](https://www.youtube.com/@StezStixFix)
- [Taskmaster](https://www.youtube.com/@Taskmaster)
- [My Mate VINCE](https://www.youtube.com/@Mymatevince)
- [Veritasium](https://www.youtube.com/@veritasium)
- [Nick Chapsas](https://www.youtube.com/@nickchapsas)
- [Adrian's Digital Basement II](https://www.youtube.com/@adriansdigitalbasement2)
- [More Fun Making It](https://www.youtube.com/@MoreFunMakingIt)
- [Epictronics](https://www.youtube.com/@Epictronics1)
- [Dave's Garage](https://www.youtube.com/@DavesGarage)
- [bigclivedotcom](https://www.youtube.com/@bigclivedotcom)
- [How Ridiculous](https://www.youtube.com/@howridiculous)
- [DIY Perks](https://www.youtube.com/@DIYPerks)
- [Ali Spagnola](https://www.youtube.com/@alispagnola)
- [JBV Creative](https://www.youtube.com/@JBVCreative)
- [Stand-up Maths](https://www.youtube.com/@standupmaths)
- [TheRetroChannel](https://www.youtube.com/@TheRetroChannel)
- [Technology Connections](https://www.youtube.com/@TechnologyConnections)
- [Tom Scott](https://www.youtube.com/@TomScottGo)
- [Computerphile](https://www.youtube.com/@Computerphile)
- [EEVblog](https://www.youtube.com/@EEVblog)
- [April Wilkerson](https://www.youtube.com/@AprilWilkerson)
- [ThioJoe](https://www.youtube.com/@ThioJoe)
- [Jeff Geerling](https://www.youtube.com/@JeffGeerling)
- [Ben Eater](https://www.youtube.com/@BenEater)
- [Steve Mould](https://www.youtube.com/@SteveMould)
- [Mark Rober](https://www.youtube.com/@MarkRober)
- [Strange Parts](https://www.youtube.com/@StrangeParts)
- [Electronoobs](https://www.youtube.com/@ELECTRONOOBS)
- [LGR](https://www.youtube.com/@LGR)
- [TylerTube](https://www.youtube.com/@TylerTube)
- [Viva La Dirt League](https://www.youtube.com/@VivaLaDirtLeague)
- [Waterjet Channel](https://www.youtube.com/@WaterjetChannel)
- [GreatScott!](https://www.youtube.com/@greatscottlab)
- [Xyla Foxlin](https://www.youtube.com/@xylafoxlin)
- [Max Fosh](https://www.youtube.com/@MaxFosh)
- [Boston Dynamics](https://www.youtube.com/@BostonDynamics)
- [Low Level Learning](https://www.youtube.com/@LowLevelLearning)
- [NDC Conferences](https://www.youtube.com/@NDC)
- [Bobby Duke Arts](https://www.youtube.com/@BobbyDukeArts)
- [Retro Recipes](https://www.youtube.com/@RetroRecipes)
- [Nate From the Internet](https://www.youtube.com/@NFTI)
- [SciManDan](https://www.youtube.com/@SciManDan)
- [vswitchzero](https://www.youtube.com/@vswitchzero)
- [element14 presents](https://www.youtube.com/@element14presents)
- [Technology Connextras](https://www.youtube.com/@TechnologyConnextras)
- [Marques Brownlee](https://www.youtube.com/@mkbhd)
- [The Action Lab](https://www.youtube.com/@TheActionLab)
- [TronicsFix](https://www.youtube.com/@Tronicsfix)
- [Modern Vintage Gamer](https://www.youtube.com/@ModernVintageGamer)
- [Amichai Mantinband](https://www.youtube.com/@amantinband)
- [I did a thing](https://www.youtube.com/@Ididathing)
- [Adam Savage’s Tested](https://www.youtube.com/@tested)
- [Defpom's Electronics Repair](https://www.youtube.com/@TheDefpom)
- [VoltLog](https://www.youtube.com/@voltlog)
- [Jelle Vermandere](https://www.youtube.com/@JelleVermandere)
- [IMSAI Guy](https://www.youtube.com/@IMSAIGuy)
- [Hydraulic Press Channel](https://www.youtube.com/@HydraulicPressChannel)
- [Paul Hibbert (Hibbert Home Tech)](https://www.youtube.com/@paulhibbert)
- [Volos Projects](https://www.youtube.com/@VolosProjects)
- [CodeOpinion](https://www.youtube.com/@CodeOpinion)
- [Necroware](https://www.youtube.com/@necro_ware)
- [Tweakers](https://www.youtube.com/@tweakers)
- [Practical Engineering](https://www.youtube.com/@PracticalEngineeringChannel)
- [Two Minute Papers](https://www.youtube.com/@TwoMinutePapers)
- [LockPickingLawyer](https://www.youtube.com/@lockpickinglawyer)
- [The Engineering Mindset](https://www.youtube.com/@EngineeringMindset)
- [Daniel Thrasher](https://www.youtube.com/@danielthrasher)
- [Dr. Becky](https://www.youtube.com/@DrBecky)
- [Milan Jovanović](https://www.youtube.com/@MilanJovanovicTech)
- [SciShow](https://www.youtube.com/@SciShow)
- [Vinheteiro](https://www.youtube.com/@Lord_Vinheteiro)
- [The Modern Rogue](https://www.youtube.com/@ModernRogue)
- [Hacksmith Industries](https://www.youtube.com/@theHacksmith)
- [TheGebs24](https://www.youtube.com/@TheGebs24)
- [Tesla](https://www.youtube.com/@tesla)
- [Raw Coding](https://www.youtube.com/@RawCoding)
- [Gamazda](https://www.youtube.com/@Gamazda)
- [Microsoft Visual Studio](https://www.youtube.com/@visualstudio)
- [Steven Kazàn](https://www.youtube.com/@stevenkazanofficial)
- [Veronica Explains](https://www.youtube.com/@VeronicaExplains)
- [Naomi Wu](https://www.youtube.com/@Naomi-Wu)
- [vkgoeswild](https://www.youtube.com/@vkgoeswildofficial)
- [IAmTimCorey](https://www.youtube.com/@IAmTimCorey)
- [LOOK MUM NO COMPUTER](https://www.youtube.com/@LOOKMUMNOCOMPUTER)
- [Sabine Hossenfelder](https://www.youtube.com/@SabineHossenfelder)
- [ByteByteGo](https://www.youtube.com/@ByteByteGo)
- [Objectivity](https://www.youtube.com/@ObjectivityVideos)
- [PeterSripol](https://www.youtube.com/@PeterSripol)
- [ColdFusion](https://www.youtube.com/@ColdFusion)
- [ToltecMerc](https://www.youtube.com/@ToltecMerc)
- [Dave Poo 2](https://www.youtube.com/@DavePoo2)
- [Unexpected Maker](https://www.youtube.com/@UnexpectedMaker)
- [Maker's Muse](https://www.youtube.com/@MakersMuse)
- [The Cherno](https://www.youtube.com/@TheCherno)
- [Tibees](https://www.youtube.com/@tibees)
- [dotnet](https://www.youtube.com/@dotnet)
- [Scary Pockets](https://www.youtube.com/@ScaryPockets)
- [Babish Culinary Universe](https://www.youtube.com/@babishculinaryuniverse)
- [Doctor Mike](https://www.youtube.com/@DoctorMike)
- [Wintergatan](https://www.youtube.com/@Wintergatan)
- [Alex](https://www.youtube.com/@FrenchGuyCooking)
- [Chubbyemu](https://www.youtube.com/@chubbyemu)
- [Life Noggin](https://www.youtube.com/@lifenoggin)
- [Unbox Therapy](https://www.youtube.com/@unboxtherapy)
- [Physics Girl](https://www.youtube.com/@physicsgirl)
- [Vsauce](https://www.youtube.com/@Vsauce)
- [MinuteEarth](https://www.youtube.com/@MinuteEarth)
- [Periodic Videos](https://www.youtube.com/@periodicvideos)
- [Sixty Symbols](https://www.youtube.com/@sixtysymbols)
- [Tech Tangents](https://www.youtube.com/@TechTangents)
- [8-Bit Show And Tell](https://www.youtube.com/@8_Bit)
- [Evan and Katelyn](https://www.youtube.com/@EvanAndKatelyn)
- [Nostalgia Nerd](https://www.youtube.com/@Nostalgianerd)
- [Retro Game Mechanics Explained](https://www.youtube.com/@RGMechEx)
- [NileRed](https://www.youtube.com/@NileRed)
- [NileBlue](https://www.youtube.com/@NileBlue)
- [Stuff Made Here](https://www.youtube.com/@StuffMadeHere)
- [The 8-Bit Guy](https://www.youtube.com/@The8BitGuy)
- [The Slow Mo Guys](https://www.youtube.com/@theslowmoguys)
- [Jan Beta](https://www.youtube.com/@JanBeta)
- [RMC - The Cave](https://www.youtube.com/@RMCRetro)
- [James Bruton](https://www.youtube.com/@jamesbruton)
- [Code Bullet](https://www.youtube.com/@CodeBullet)
- [This Old Tony](https://www.youtube.com/@ThisOldTony)
- [Rein Peeters](https://www.youtube.com/@reinpeeters)
- [bitluni](https://www.youtube.com/@bitlunislab)
- [ElectroBOOM](https://www.youtube.com/@ElectroBOOM)
- [Displaced Gamers](https://www.youtube.com/@DisplacedGamers)
- [suckerpinch](https://www.youtube.com/@tom7)
- [there oughta be](https://www.youtube.com/@ThereOughtaBe)
- [StezStix Mix](https://www.youtube.com/@StezStixMix)
- [Up and Atom](https://www.youtube.com/@upandatom)
- [Simone Giertz](https://www.youtube.com/@simonegiertz)
- [Doctor Volt](https://www.youtube.com/@DoctorVolt)
- [MattKC](https://www.youtube.com/@MattKC)
- [TomSka & Friends](https://www.youtube.com/@TomSkaAndFriends)
- [AlphaPhoenix](https://www.youtube.com/@AlphaPhoenixChannel)
- [engineerguy](https://www.youtube.com/@engineerguyvideo)
- [Game Maker's Toolkit](https://www.youtube.com/@GMTK)
- [Matthias random stuff](https://www.youtube.com/@matthiasrandomstuff2221)
- [The Science Asylum](https://www.youtube.com/@ScienceAsylum)
- [Mattias Krantz](https://www.youtube.com/@Mattiaskrantz)
- [Captain Disillusion](https://www.youtube.com/@CaptainDisillusion)
- [TheBackyardScientist](https://www.youtube.com/@TheBackyardScientist)
- [Allen Pan](https://www.youtube.com/@allenpan)
- [sina-drums](https://www.youtube.com/@sina-drums)
- [atomic14](https://www.youtube.com/@atomic14)
- [Jeri Ellsworth](https://www.youtube.com/@jeriellsworth)
- [Ben Heck Hacks](https://www.youtube.com/@BenHeckHacks)
- [Jonas Tyroller](https://www.youtube.com/@JonasTyroller)
- [colinfurze](https://www.youtube.com/@colinfurze)
- [Alec Steele](https://www.youtube.com/@AlecSteele)
- [Brainiac75](https://www.youtube.com/@brainiac75)
- [Andreas Spiess](https://www.youtube.com/@AndreasSpiess)
- [Mike Boyd](https://www.youtube.com/@MikeBoyd)
- [PomplamooseMusic](https://www.youtube.com/@Pomplamoose)
- [GameHut](https://www.youtube.com/@GameHut)
- [SmarterEveryDay](https://www.youtube.com/@smartereveryday)
- [Scott Hanselman](https://www.youtube.com/@shanselman)
- [Ahoy](https://www.youtube.com/@XboxAhoy)
- [Taskmaster AU](https://www.youtube.com/@TaskmasterAU)
- [Cranktown City](https://www.youtube.com/@cranktowncity)
- [FoxTech](https://www.youtube.com/@Fox-Tech)
- [stacksmashing](https://www.youtube.com/@stacksmashing)
- [NCommander](https://www.youtube.com/@NCommander)
- [Yuval Salomon](https://www.youtube.com/@YuvalSalomon)
- [Mr SolderFix](https://www.youtube.com/@mrsolderfix3996)
- [Borderline OCD](https://www.youtube.com/@BorderlineOCD)
- [Marco Reps](https://www.youtube.com/@reps)
- [Learn Embedded Systems](https://www.youtube.com/@LearnEmbeddedSystems)
- [Quint BUILDs](https://www.youtube.com/@QuintBUILDs)
- [The Retro Shack](https://www.youtube.com/@TheRetroShack)
- [Ralph S Bacon](https://www.youtube.com/@RalphBacon)
- [Andreas Kling](https://www.youtube.com/@awesomekling)
- [styropyro](https://www.youtube.com/@styropyro)
- [tom cardy](https://www.youtube.com/@tomcardy1)
- [Noel's Retro Lab](https://www.youtube.com/@NoelsRetroLab)
- [LevelUp](https://www.youtube.com/@LevelUppp)
- [ortoPilot](https://www.youtube.com/@ortopilot)
- [Tyler Bell](https://www.youtube.com/@TylerBellMakes)
- [Carl Bugeja](https://www.youtube.com/@CarlBugeja)
- [Kevin Darrah](https://www.youtube.com/@Kevindarrah)
- [Julian Ilett](https://www.youtube.com/@JulianIlett)
- [Schematix](https://www.youtube.com/@Schematix)
- [AddOhms](https://www.youtube.com/@AddOhms)
- [Coding Secrets](https://www.youtube.com/@CodingSecrets)
- [Kyle Hill](https://www.youtube.com/@kylehill)
- [Awkward Puppets](https://www.youtube.com/@AwkwardPuppets)
- [Tom Stanton](https://www.youtube.com/@TomStantonEngineering)
- [Brian Lagunas](https://www.youtube.com/@BrianLagunas)
- [Branch Education](https://www.youtube.com/@BranchEducation)
- [BraaiTV](https://www.youtube.com/@BraaiTV)
- [DIY Machines](https://www.youtube.com/@DIYMachines)
- [KeenSystems](https://www.youtube.com/@keensystems2185)
- [Because Science](https://www.youtube.com/@becausescience)
- [Video Game Animation Study](https://www.youtube.com/@VideoGameAnimationStudy)
- [D!NG](https://www.youtube.com/@dingsauce)
- [Socratica](https://www.youtube.com/@Socratica)
- [Medlife Crisis](https://www.youtube.com/@MedlifeCrisis)
- [NancyPi](https://www.youtube.com/@NancyPi)
- [Zimri Mayfield](https://www.youtube.com/@zimrimayfield)
- [LiveOverflow](https://www.youtube.com/@LiveOverflow)
- [Brackeys](https://www.youtube.com/@Brackeys)
- [Neuro Transmissions](https://www.youtube.com/@neurotransmissions)
- [Nerdphilia](https://www.youtube.com/@nerdphilia)
- [Elise Trouw](https://www.youtube.com/@elisetrouw)
- [The Coding Train](https://www.youtube.com/@TheCodingTrain)
- [EverythingApplePro E A P](https://www.youtube.com/@EverythingApplePro)
- [Evan Kale](https://www.youtube.com/@kale)
- [Stephen Robinson](https://www.youtube.com/@stephenrobinson52)
- [William Osman](https://www.youtube.com/@williamosman)
- [javidx9](https://www.youtube.com/@javidx9)
- [Danu](https://www.youtube.com/@danu7718)
- [Steven Lam](https://www.youtube.com/@mijnpriveaccount)
- [3Blue1Brown](https://www.youtube.com/@3blue1brown)
- [The Vintage Space](https://www.youtube.com/@AmyShiraTeitel)
- [Sciencium](https://www.youtube.com/@sciencium)
- [DÆrik](https://www.youtube.com/@TeslaInventory)
- [PBS Infinite Series](https://www.youtube.com/@pbsinfiniteseries)
- [Bruce Yeany](https://www.youtube.com/@YeanyScience)
- [Techmoan](https://www.youtube.com/@Techmoan)
- [Thought Café](https://www.youtube.com/@ThoughtBubbler)
- [TheHappieCat](https://www.youtube.com/@TheHappieCat)
- [Wendover Productions](https://www.youtube.com/@Wendoverproductions)
- [Cody'sLab](https://www.youtube.com/@theCodyReeder)
- [DennieBee](https://www.youtube.com/@morphiesta)
- [LucaIII](https://www.youtube.com/@lucaiii8188)
- [ScoopexUs](https://www.youtube.com/@ScoopexUs)
- [The Slow Mo Guys 2](https://www.youtube.com/@TheSlowMoGuys2)
- [PBS Space Time](https://www.youtube.com/@pbsspacetime)
- [Mathologer](https://www.youtube.com/@Mathologer)
- [SciShow Space](https://www.youtube.com/@scishowspace)
- [Applied Science](https://www.youtube.com/@AppliedScience)
- [LastWeekTonight](https://www.youtube.com/@LastWeekTonight)
- [Numberphile](https://www.youtube.com/@numberphile)
- [Matt Mulholland](https://www.youtube.com/@MattMulhollandParty)
- [Kurzgesagt – In a Nutshell](https://www.youtube.com/@kurzgesagt)
- [CGP Grey](https://www.youtube.com/@CGPGrey)
- [singingbanana](https://www.youtube.com/@singingbanana)
- [Vihart](https://www.youtube.com/@Vihart)
- [minutephysics](https://www.youtube.com/@MinutePhysics)
- [DeepSkyVideos](https://www.youtube.com/@DeepSkyVideos)

> Are you using any other extensions for YouTube that allow you to customize your subscriptions by any chance? This could likely cause conflicts between the two extensions.

Nope. I am using the following extensions:

- [Adblock Plus - free ad blocker](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb) 3.17
- [Awesome ChatGPT Screenshot & Screen Recorder](https://chrome.google.com/webstore/detail/awesome-chatgpt-screensho/nlipoenfbbikpbjkfpfillcgkoblgpmj) 4.3.82
- [Google Docs Offline](https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi) 1.62.0
- [Hide YouTube Shorts](https://chrome.google.com/webstore/detail/hide-youtube-shorts/aljlkinhomaaahfdojalfmimeidofpih) 1.6.8
- [LastPass: Free Password Manager](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd) 4.115.0
- [Marktplaats zonder spam](https://chrome.google.com/webstore/detail/marktplaats-zonder-spam/lekhkeegnegccgaoakphligfonjmaodh) 2.2.2.1
- [Moderator toolbox for reddit](https://chrome.google.com/webstore/detail/moderator-toolbox-for-red/jhjpjhhkcbkmgdkahnckfboefnkgghpo) 6.1.4: "Delaying Donkey"
- [Save to Pocket](https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj) 4.0.6

> Come to think of it, I don't recall ever seeing a Shorts Shelf on the Subscriptions page before and I am unable to get one to appear on my own no matter how hard I try, so this could very well be a new thing.

I don't know, but I've been seeing them for quite some time on my subscriptions list

> Could you go to the Subscriptions page > right click anywhere on the page > click "view page source", then copy the entire contents of the pages HTML, paste it into a .txt file and upload it here so I can take a look at it? Because as of right now I am unable to repro and no one has mentioned having this issue.

Sure. [Here you go](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11710781/yt.txt). (I have taken the liberty to 'tidy' the HTML a little).


FWIW: My subscriptions bookmark links to: https://www.youtube.com/feed/subscriptions?flow=2 which gets redirected to https://www.youtube.com/feed/subscriptions. Not sure what the flow=2 does (or, more likely, did) but going to https://www.youtube.com/feed/subscriptions directly still shows the shorts. And, again, I've been seeing them there for quite a while now. Like, months at least.

**Comment by zevnda** [comment]
> I have over 200 subscriptions, they're not in alphabetical order:

Hmm, maybe after a certain number of subscriptions YouTube just stops ordering them lol not sure

> Sure. [Here you go](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11710781/yt.txt). (I have taken the liberty to 'tidy' the HTML a little).

Sorry, my mistake, forgot YouTube renders everything dynamically so no useful data from viewing the page source. Instead, can you follow the same steps but instead of clicking "view page source" click "inspect element", wait for the dev tools window to popup, scroll right to the top of the element tab, right click the opening <html> tag, go down to copy > copy element. Paste that in a .txt file and send that instead. Just make sure the page had completely finished rendering all the videos and stuff.

> FWIW: My subscriptions bookmark links to: https://www.youtube.com/feed/subscriptions?flow=2 which gets redirected to https://www.youtube.com/feed/subscriptions. Not sure what the flow=2 does (or, more likely, did) but going to https://www.youtube.com/feed/subscriptions directly still shows the shorts. And, again, I've been seeing them there for quite a while now. Like, months at least.

Thanks. Yeah `flow=1` and `flow=2` are just the difference between Grid and List view. `flow=2` being List view which is what you're using based off the screenshot. Does the Shorts Shelf only appear in List view or is it in Grid view as well?

**Comment by RobThree** [comment]
> Sorry, my mistake [...] Paste that in a .txt file and send that instead.

[Here you go](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11711178/yt.txt)

> Does the Shorts Shelf only appear in List view or is it in Grid view as well?

I don't seem to get shorts in the grid view.

I also tried disabling Adblock Pro but no difference.

**Comment by zevnda** [comment]
> [Here you go](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11711178/yt.txt)

Thanks for doing that mate.

I believe I've fixed this issue. Though, I can't push the fix as a update to the CWS version until I can verify it works and doesn't break anything else _(though it likely won't)_.

If you're up for it, would you mind testing to see if it works? You can download the .zip file from [this branch](https://github.com/ProbablyRaging/hide-youtube-shorts/tree/feat(Hide-shorts-shelves-on-the-subscriptions-page)), install the unpacked version following [these steps](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked). Make sure you disable the official version first. Just test it out for a few days and report back.

If not, I will have to wait until I can somehow verify it myself.

**Comment by RobThree** [comment]
> If you're up for it, would you mind testing to see if it works?

I won't mind at all. But I'll have to leave that for tomorrow or later this week, sorry.

**Comment by RobThree** [comment]
I downloaded the zip-file, extracted it, extensions are already in developer mode, clicked load unpacked, selected the unpacked directory and then I get:

<img width="496" alt="Screenshot 2023-06-11 at 12 32 26" src="https://github.com/ProbablyRaging/hide-youtube-shorts/assets/607888/9ef5223c-0271-4319-834a-483d39b9bcf8">

**Comment by zevnda** [comment]
> I downloaded the zip-file, extracted it, extensions are already in developer mode, clicked load unpacked, selected the unpacked directory and then I get:

Sorry mate, give this a try, make sure the folder you're selecting has `manifest.json` in the root

[hide-youtube-shorts-1.6.9-b.zip](https://github.com/ProbablyRaging/hide-youtube-shorts/files/11714400/hide-youtube-shorts-1.6.9-b.zip)

**Comment by RobThree** [comment]
That properly installed.

Can confirm shorts are now gone though I saw them briefly before they disappeared. I think this is 'by design'?

**Comment by zevnda** [comment]
Good to hear!

Yeah, you will usually see a quick glimpse of them before they dissapear as the context script waits for the DOM to be loaded before it starts running any functions to remove elements.

But glad to hear it's working. Test it out for a few days and let me know if you have any issues at all. If all is good I will merge it with the main branch 🍻

**Comment by RobThree** [comment]
I haven't seen any shorts since! 👍  I think it's safe to add this.

**Comment by zevnda** [comment]
> I haven't seen any shorts since! 👍 I think it's safe to add this.

Thank you for testing mate. Have added this fix and it should be live on CWS within 24 hours 🍻
