### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by tmustaine** [ProbablyRaging/hide-youtube-shorts#20]
### What do you need support with?

Hide-Youtube-Shorts disabled itself to request new permissions to "Read your browsing history."

Is this a bug or a requirement of new versions of this extension?  Seems unnecessary for this extension.
![image](https://github.com/ProbablyRaging/hide-youtube-shorts/assets/3096342/feb43061-66bd-40dd-a366-207bc660e2e1)

**Comment by Steven-N** [comment]
They've replied to some folks on the extension reviews about the reason why.

\
They also appear to have reverted the change: https://github.com/ProbablyRaging/hide-youtube-shorts/releases

**Comment by zevnda** [comment]
Thank you for opening a ticket.

Yes, these new permission changes have been reverted in version `1.6.14` with afc413e290bab2262d16441cbffe574b4f1acd29.

The update should be live on the Chrom Web Store within 24 hours.

If you are concerned about the permission, you can disable/uninstall the extension temporarily until the new update is live. I will make an announcement on our Discord once the new update is live here https://discord.com/invite/HAFP4P7Dfr

**Comment by tmustaine** [comment]
Awesome, thanks! Love the extension. Appreciate it.
