### ISSUE TITLE
Hiding subscription feed shorts also hides the channel shorts when navigating from subscription feed

### ISSUE THREAD

**Issue by bk7312** [ProbablyRaging/hide-youtube-shorts#25]
If we hide the subscription feed shorts but not the shorts tab in the channel page, the shorts in the channel's shorts tab is also hidden. But only when navigating from the subscription page to the channel page. The shorts in the channel's shorts tab still show if we refresh the page or navigate directly to the channel's shorts tab. 

Settings:
Feed Pages - Subscriptions Feed Shorts - ON
Channel Pages - Shorts Tab - OFF

How to reproduce:
1. Go to https://www.youtube.com/feed/subscriptions, shorts are hidden
2. Click on any channel https://www.youtube.com/@<channel>/ and go to their shorts tab
3. Expected to see shorts but no shorts shown
4. Refresh the channel's shorts page or go directly to https://www.youtube.com/@<channel>/shorts
5. Shorts shown as normal

**Comment by zevnda** [comment]
Thank you for reporting this! 

I was able to reproduce the issue as well and will work of a fix ASAP. I'll update this issue once done.

**Comment by zevnda** [comment]
This has been fixed in `1.6.15.1` with 1381626f7fbfc5576456c817410ca3f6f426573f. Should be live on the CWS within 24 hours.

Thanks again for the report 👍

**Comment by bk7312** [comment]
Thanks, that was fast!
