### ISSUE TITLE
Request to add a hide "Originals" toggle

### ISSUE THREAD

**Issue by cadtek91** [ProbablyRaging/hide-youtube-shorts#26]
### Describe the feature

Just a request to add the option for hiding the "Originals" link in the navigation menu.

**Comment by zevnda** [comment]
Thanks for the feature request.

Would you be able to show me the "Originals" link that you're referring to. I actually don't have it on my navigation menu. I think this link might be region/user specific maybe?

**Comment by cadtek91** [comment]
[Screenshot](https://imgur.com/njsRkBj)

Now that I think about it some more, I think it's YouTube Premium only.  Maybe it's better via uBlock Origin instead via a [custom filter](https://gist.github.com/gidoBOSSftw5731/15721a09a8be4191baeb4c5606d1a199#file-ytoriginalssidebar-ubo)?

**Comment by zevnda** [comment]
I think you might be right about it being a Premium feature. A UBO filter sounds like a reasonable solution to me.

At this time I won't be adding an option for this. But I appreciate your suggestion 🙂thank you!
