### ISSUE TITLE
Hide watched videos from subscription feed

### ISSUE THREAD

**Issue by qxsnap** [ProbablyRaging/hide-youtube-shorts#27]
### Describe the feature

Would the method used by this app also be able to hide already-watched videos from the subscription feed?  Such as removing videos that are 90% or more complete?

This has baffled me for years why watched videos can't be filtered from the subscription feed view.  The only available technique is to manually "Hide" a video after watching it.

**Comment by zevnda** [comment]
Thank you for the suggestion.

I've not looked in to it, but I believe it is definitely possible as, if I'm not mistaken, there are browser extensions that already exist that do what you're asking, such as [FreshView for YouTube™](https://chrome.google.com/webstore/detail/freshview-for-youtube/eckknmnfoohbeklmjlidmfdlakndcfkm), though I've not used it personally, it appears to do what you're looking for.

I might look in to adding something similar to HYS when I get the chance, but I can't guarantee it will get added. If it does I will update this thread 👍

Thanks again for the suggestion!
