### ISSUE TITLE
Shorts are still showing in Subscription feed List view

### ISSUE THREAD

**Issue by kalogane** [ProbablyRaging/hide-youtube-shorts#29]
### Describe the issue

I use the List view on my Subscriptions feed by default and they added a large section with all the Shorts from my sub box that appears under the first video in the subscription list and it takes up nearly half the page real estate, which is what drove me to find this plugin (amazing work btw!)

The plugin removes everything as expected, except this specific section in the List view Subscriptions.

When I switch to Grid view and I flick the `Subscriptions Feed Shorts` toggle in the extension, the Shorts in the Grid view disappear and appear as expected. However, the same behaviour does not work in List view.

### What version of HYS are you using?

Latest version

### What browsers are you seeing the problem on?

Chrome

### Latest browser version?

Yes

**Comment by zevnda** [comment]
Thanks for opening an issue. 

It would appear YouTube recently added a shorts shelf to the list view on the subscriptions page, should be an easy fix and I'll have an update for it within the week. I will update this issue once that is done!

**Comment by zevnda** [comment]
Fixed in `1.6.15.2` with 3f8c74ffbafee487f1f0e4248f6eae29690d63ce

This update should be live on the CWS within 24 hours. Thanks again for the report!

**Comment by kalogane** [comment]
Thank you for the speedy response and fix! This extension absolutely rocks
