### ISSUE TITLE
Compatibility with other languages

### ISSUE THREAD

**Issue by wallacejerry** [ProbablyRaging/hide-youtube-shorts#3]
Hello guys,
I was debugging the extension to try to understand why it wasn't working on the submissions page (I only saw the issue on GitHub afterwards), and found two problems that can be solved at once...

The condition used to identify the current page is similar to this:
`if (document.title.toLowerCase() === 'subscriptions - youtube')`

- But in other languages, it is displayed in a translated form, becoming like: "Inscrições - Youtube" (Portuguese).
- And also, in the title of my page there was a notification on Youtube, looking like this: "(1) Inscrições - Youtube".

In both cases it would not work.

So this is my suggestion:
Instead of using the title of the page in the condition, could we use the URL of the page (with document.URL for example)?
I believe that this way it would be more secure, and would avoid problems with translations and notifications. I can code it if you like the idea hehe

**Comment by zevnda** [comment]
Thank you. Didn't even occur to me that there would be issues with different title locales. Have resorted to checking `location.href` instead. Fixed with ab69a38

**Comment by wallacejerry** [comment]
Nice, thank you very much :D
