### ISSUE TITLE
Explain why this extension needs access to all hosts

### ISSUE THREAD

**Issue by MrVoltz** [ProbablyRaging/hide-youtube-shorts#30]
Hi, I've been using your extension for a long time, but one day I saw the new requirement for access to all hosts and tabs. Is this permission really necessary for this extension to work?

https://github.com/ProbablyRaging/hide-youtube-shorts/blame/111044383cccc22517f71a8386eb8aa0ea2bf367/public/manifest.json#L13

**Comment by zevnda** [comment]
Thanks for reaching out. This question has already been answered in #24 

> I've changed the way I declare hosts, instead of declaring just the previous youtube domains, I've opted to delcare `<all_urls>` in order for the recent changes to work correctly without the intrusive `reads browsing history` warning. The changes in question are the use of `insertCSS()` and `executeScript()` methods.

> ### If you want to manually limit which sites the extension can access; 
> - Go to `chrome://extensions` _(or manage extensions)_
> - Select `Details` on the extension
> - Under `Site access` you can allow the extension to only work on specific sites. Make sure it works on `www.youtube.com` and `m.youtube.com` if you use HYS on mobile browser.
